name: NPM Publishing

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm set audit false
      - run: npm ci
      - run: npm run build
      - run: printf '\n//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> .npmrc
      - run: npm publish --access public
        env:
          # `secrets.NPM_TOKEN` references a GitHub Secret configured for this repo or organization,
          # and is used to authenticate for the NPM publish command.
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
